= SAÉ S3.01 2024-2025

image::https://classroom.github.com/assets/open-in-vscode-2e0aaae1b6195c2367325f4f02e2d04e9abb55f0b24a779b69b11b9e10269abc.svg["Open in Visual Studio Code", link="https://classroom.github.com/online_ide?assignment_repo_id=16928608&assignment_repo_type=AssignmentRepo"]

:icons: font
:models: models
:experimental:
:incremental:
:numbered:
:toc: macro
:window: _blank
:correction!:



// Useful definitions
:asciidoc: http://www.methods.co.nz/asciidoc[AsciiDoc]
:icongit: icon:git[]
:git: http://git-scm.com/[{icongit}]
:plantuml: https://plantuml.com/fr/[plantUML]
:vscode: https://code.visualstudio.com/[VS Code]

ifndef::env-github[:icons: font]
// Specific to GitHub
ifdef::env-github[]
:correction:
:!toc-title:
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
:icongit: Git
endif::[]

:baseURL: https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2b12

// Tags
image:{baseURL}/actions/workflows/blank.yml/badge.svg["Bidon"]
// image:{baseURL}/actions/workflows/build.yml/badge.svg["Build"]
// image:{baseURL}/actions/workflows/tests.yml/badge.svg["Tests"]
image:https://img.shields.io/badge/License-MPL%202.0-brightgreen.svg["License: MPL-2.0", link="https://opensource.org/licenses/MPL-2.0"]

//---------------------------------------------------------------

toc::[]

== *Equipe*

*Projet est réalisé par:*
|===

| NOM | RÔLE
| https://github.com/ImHereForWhat/[Mathys Laguilliez] | Dev
| https://github.com/Hextaz[Nolhan Biblocque] | Dev
| https://github.com/VictorJockin[Victor Jockin] | Scrum master
| https://github.com/Ezeloss[Léo Guinvarc'h] | Dev
| https://github.com/34lks66[Mucahit Lekesiz] | Product Owner
|===

Tuteur/tutrice enseignant(e) de l'équipe:: mailto:jean-michel.bruel@univ-tlse2.fr[JMB]


== *Réalisations*

=== Livrables

|===
3+^| *LIVRABLES*
3+|
| SEMAINE | SOLUTION | LIEN
.4+| 45 | Web | https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2b12/issues[Backlog produit (Product backlog)]
| Web | https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2b12/milestones[Backlog de sprint 1]
| Web | https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2b12/blob/master/docs/document_de_conception/document_conception.adoc[Document de conception]
| IoT | https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2b12/tree/master/solution%20iot[Clients MQTT python] +
• https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2b12/tree/master/solution%20iot/client_mqtt_version1[Clients MQTT autonaume] +
• https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2b12/tree/master/solution%20iot/client_mqtt_version2[Clients MQTT avec fichier de configuration]
|===

=== Documentations

|===
| *DOCUMENTATIONS*
|
| SOLUTION WEB
| https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2b12/blob/master/docs/document_de_conception/document_conception.adoc[Document de conception]
|
| SOLUTION IOT
| _À venir._
|
|===

== *Gestion de projet & Qualité*

Chaque sprint (semaine) vous devrez livrer une nouvelle version de votre application (release).
Utilisez pour cela les fonctionnalités de GitHub pour les https://docs.github.com/en/repositories/releasing-projects-on-github[Releases].

De plus ce fichier `README.adoc` devra être à jour des informations suivantes :

- Version courante : https://github.com/IUT-Blagnac/sae3-01-template/releases/tag/v0.1.2[v0.1.2]
- Lien vers la doc technique
- Lien vers la doc utilisateur
- Liste des (ou lien vers les) User Stories (ToDo/Ongoing/Done) et % restant
- Tests unitaires et plans de test
- Indicateurs de qualité du code (dette technique)
- ... tout autre élément que vous jugerez utiles pour démontrer la qualité de votre application

== Gestion de projet & Qualité
=== Evaluation bi-hebdomadaire

ifdef::env-github[]
image:https://docs.google.com/spreadsheets/d/e/2PACX-1vSACcYeKaH_ims3faegSLAFJ9s5_Kd9Fbyi4ODEb8BTN5OnUXWenVGhlVPo84yQDhTkTj3f9nXiluh1/pubchart?oid=935875429&amp;format=image[link=https://docs.google.com/spreadsheets/d/e/2PACX-1vSACcYeKaH_ims3faegSLAFJ9s5_Kd9Fbyi4ODEb8BTN5OnUXWenVGhlVPo84yQDhTkTj3f9nXiluh1/pubchart?oid=935875429&amp;format=image]
endif::[]

ifndef::env-github[]
++++
<iframe width="786" height="430" seamless frameborder="0" scrolling="no" src="https://docs.google.com/spreadsheets/d/e/2PACX-1vSACcYeKaH_ims3faegSLAFJ9s5_Kd9Fbyi4ODEb8BTN5OnUXWenVGhlVPo84yQDhTkTj3f9nXiluh1/pubchart?oid=935875429&amp;format=interactive"></iframe>
endif::[]

=== retour sprint 1 / Initialisation du dépôt
Enlevez les consignes du readme ! Mettre les rôles de chacun. Issues/ US :  Pensez à mettre les finalités, les critères d'acceptabilité et les tâches liées pour réaliser la US. Il faut relier votre  Backlog sprint à votre projet (créer une colonne en plus dans votre board où vous mettez les US à traiter dans le sprint). Idem il faut rattacher les tâches/issues au projet. doc: Pensez à présenter le contexte dans la doc de conception et à citer votre client. Il me manque : cahier de tests et doc utilistateur et tech à au moins initialiser à ce stade. Il me manque une release ou au moins une date de première release pour le Web.

