= SAÉ S3.01 2024-2025

image::https://classroom.github.com/assets/open-in-vscode-2e0aaae1b6195c2367325f4f02e2d04e9abb55f0b24a779b69b11b9e10269abc.svg["Open in Visual Studio Code", link="https://classroom.github.com/online_ide?assignment_repo_id=16928608&assignment_repo_type=AssignmentRepo"]

:icons: font
:models: models
:experimental:
:incremental:
:numbered:
:toc: macro
:window: _blank
:correction!:



// Useful definitions
:asciidoc: http://www.methods.co.nz/asciidoc[AsciiDoc]
:icongit: icon:git[]
:git: http://git-scm.com/[{icongit}]
:plantuml: https://plantuml.com/fr/[plantUML]
:vscode: https://code.visualstudio.com/[VS Code]

ifndef::env-github[:icons: font]
// Specific to GitHub
ifdef::env-github[]
:correction:
:!toc-title:
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
:icongit: Git
endif::[]

:baseURL: https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2b12

// Tags
image:{baseURL}/actions/workflows/blank.yml/badge.svg["Bidon"]
// image:{baseURL}/actions/workflows/build.yml/badge.svg["Build"]
// image:{baseURL}/actions/workflows/tests.yml/badge.svg["Tests"]
image:https://img.shields.io/badge/License-MPL%202.0-brightgreen.svg["License: MPL-2.0", link="https://opensource.org/licenses/MPL-2.0"]

//---------------------------------------------------------------

TIP: Pensez à mettre à jour les infos dans ce fichier pour que les badges pointent sur les résultats effectifs de vos intégrations continue ou sur la bonne licence logicielle.

Ce fichier `README.adoc` (dont vous lisez sûrement le rendu HTML automatiquement effectué par GitHUb), fait partie du dépôt initial cloné à partir du lien GitHub classroom qui vous a été donné en cours (https://classroom.github.com/a/fePVlfpN).
Vous trouverez le dépôt "template" qui a servi de base ici : https://github.com/IUT-Blagnac/sae3-01-template. En complément du cours Moodle de la SAE 3.01 (cf. <<liensUtiles>>), ce dépôt template vous permet d'accéder à des exemples d'https://github.com/IUT-Blagnac/sae3-01-template/issues[issues], de https://github.com/IUT-Blagnac/sae3-01-template/releases[releases], ou d'autres artefacts à venir.

toc::[]

== *Equipe*

Projet est réalisé par::

- https://github.com/ImHereForWhat/[Mathys Laguilliez]
- https://github.com/Hextaz[Nolhan Biblocque]
- https://github.com/VictorJockin[Victor Jockin]
- https://github.com/Ezeloss[Léo Guinvarc'h]
- https://github.com/34lks66[Mucahit Lekesiz]

Tuteur/tutrice enseignant(e) de l'équipe:: mailto:jean-michel.bruel@univ-tlse2.fr[JMB]


== *Réalisations*

=== Livrables

|===
3+^| *LIVRABLES*
3+|
| SEMAINE | SOLUTION | LIEN
.4+| 45 | Web | https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2b12/issues[Backlog produit (Product backlog)]
| Web | https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2b12/milestones[Backlog de sprint 1]
| Web | https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2b12/blob/master/docs/document_de_conception/document_conception.adoc[Document de conception]
| IoT | https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2b12/tree/master/solution%20iot[Clients MQTT python] +
• https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2b12/tree/master/solution%20iot/client_mqtt_version1[Clients MQTT autonaume] +
• https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2b12/tree/master/solution%20iot/client_mqtt_version2[Clients MQTT avec fichier de configuration]
|===

=== Documentations

|===
| *DOCUMENTATIONS*
|
| SOLUTION WEB
| https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2b12/blob/master/docs/document_de_conception/document_conception.adoc[Document de conception]
|
| SOLUTION IOT
| _À venir._
|
|===

== *Gestion de projet & Qualité*

Chaque sprint (semaine) vous devrez livrer une nouvelle version de votre application (release).
Utilisez pour cela les fonctionnalités de GitHub pour les https://docs.github.com/en/repositories/releasing-projects-on-github[Releases].

De plus ce fichier `README.adoc` devra être à jour des informations suivantes :

- Version courante : https://github.com/IUT-Blagnac/sae3-01-template/releases/tag/v0.1.2[v0.1.2]
- Lien vers la doc technique
- Lien vers la doc utilisateur
- Liste des (ou lien vers les) User Stories (ToDo/Ongoing/Done) et % restant
- Tests unitaires et plans de test
- Indicateurs de qualité du code (dette technique)
- ... tout autre élément que vous jugerez utiles pour démontrer la qualité de votre application

Voici un exemple d'évaluation :

ifdef::env-github[]
image:https://docs.google.com/spreadsheets/d/e/2PACX-1vTc3HJJ9iSI4aa2I9a567wX1AUEmgGrQsPl7tHGSAJ_Z-lzWXwYhlhcVIhh5vCJxoxHXYKjSLetP6NS/pubchart?oid=1850914734&amp;format=image[link=https://docs.google.com/spreadsheets/d/e/2PACX-1vTc3HJJ9iSI4aa2I9a567wX1AUEmgGrQsPl7tHGSAJ_Z-lzWXwYhlhcVIhh5vCJxoxHXYKjSLetP6NS/pubchart?oid=1850914734&amp;format=image]
endif::[]

ifndef::env-github[]
++++
<iframe width="786" height="430" seamless frameborder="0" scrolling="no" src="https://docs.google.com/spreadsheets/d/e/2PACX-1vTc3HJJ9iSI4aa2I9a567wX1AUEmgGrQsPl7tHGSAJ_Z-lzWXwYhlhcVIhh5vCJxoxHXYKjSLetP6NS/pubchart?oid=1850914734&amp;format=image"></iframe>
++++
endif::[]
