= SAÉ S3.01 2024-2025

image::https://classroom.github.com/assets/open-in-vscode-2e0aaae1b6195c2367325f4f02e2d04e9abb55f0b24a779b69b11b9e10269abc.svg["Open in Visual Studio Code", link="https://classroom.github.com/online_ide?assignment_repo_id=16928608&assignment_repo_type=AssignmentRepo"]

:icons: font
:models: models
:experimental:
:incremental:
:numbered:
:toc: macro
:window: _blank
:correction!:



// Useful definitions
:asciidoc: http://www.methods.co.nz/asciidoc[AsciiDoc]
:icongit: icon:git[]
:git: http://git-scm.com/[{icongit}]
:plantuml: https://plantuml.com/fr/[plantUML]
:vscode: https://code.visualstudio.com/[VS Code]

ifndef::env-github[:icons: font]
// Specific to GitHub
ifdef::env-github[]
:correction:
:!toc-title:
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
:icongit: Git
endif::[]

:baseURL: https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2b12

// Tags
image:{baseURL}/actions/workflows/blank.yml/badge.svg["Bidon"]
// image:{baseURL}/actions/workflows/build.yml/badge.svg["Build"]
// image:{baseURL}/actions/workflows/tests.yml/badge.svg["Tests"]
image:https://img.shields.io/badge/License-MPL%202.0-brightgreen.svg["License: MPL-2.0", link="https://opensource.org/licenses/MPL-2.0"]

//---------------------------------------------------------------

toc::[]




== *Equipe et Rôles*

Le projet est réalisé par :

|===
2+^| *Equipe G2b12*
2+|
| Nom | Rôle |
https://github.com/VictorJockin[*Victor Jockin*] | *Scrum Master* |
https://github.com/34lks66[*Mucahit Lekesiz*] | *Product Owner* |
https://github.com/Hextaz[*Nolhan Biblocque*] | *Développeur* |
https://github.com/Ezeloss[*Léo Guinvarc'h*] | *Développeur* |
https://github.com/ImHereForWhat/[*Mathys Laguilliez*] | *Développeur* 
|===

Développement avec la méthode de conduite de projet Scrum.

Tuteur enseignant de l'équipe : mailto:jean-michel.bruel@univ-tlse2.fr[*Jean-Michel Bruel*]


== *Contexte général*

Le projet est à réaliser dans le cadre de la SAE 3.01 Conception et Développement d'application. Il a pour objectif de développer une solution E-commerce pour l’entreprise *Woohp resell*, PME spécialisée dans la vente de gadgets d’espionnage et de technologies de sécurité. 

L’entreprise fondée initialement par l'organisation WOOHP (World Organization Of Human Protection) a la volonté d'élargir son marché en se faisant connaître auprès du grand public et ainsi assurer la continuité de son héritage. 

Cette démarche de digitalisation de l'offre via un site E-commerce s'inscrit dans cette dynamique.



=== *Liens utiles*

Vous trouverez ci-dessous les liens utilisés pour l'initialisation et la réalisation de ce projet dans le cadre de la SAE 3.01 :

|===
| *Intitulés*| *Liens*
|Github Classroom | https://classroom.github.com/assignment-invitations/c5ec3e74eaeb5ffc224e91915647cedc
|Cours Moodle SAE 3.01 | https://webetud.iut-blagnac.fr/course/view.php?id=841
|Dépôt Template initial| https://github.com/IUT-Blagnac/sae3-01-template
|===


== *Réalisations*

=== Livrables

Vous trouverez ci-dessous les travaux et livrables réalisés par l'équipe classées au fur et à mesure de l'avancée du projet :

|===
3+^| *LIVRABLES*
3+|
| *SEMAINE* | *SOLUTION* |*LIEN*
.7+| 45 | Web | https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2b12/issues[Backlog produit (Product backlog)]
| | https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2b12/milestones[Backlog de sprint 1]
| | https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2b12/blob/master/solution%20web/docs/document_de_conception/document_conception.adoc[Document de conception]
| IoT | https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2b12/tree/master/solution%20iot[Clients MQTT python] 
| | https://github.com/IUT-Blagnac/sae-3-01-devapp2024-2025-g2b12/tree/master/solution%20iot/client_mqtt_version1[Clients MQTT autonaume] 
| | https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2b12/tree/master/solution%20iot/client_mqtt_version2[Clients MQTT avec fichier de configuration]
| GPO | https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2b12/blob/master/GPO/CR_R%C3%A9union/Contrat%20d'%C3%A9quipe.pdf[Contrat d'équipe]
.2+| 46 | GPO| https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2b12/blob/master/GPO/CR_R%C3%A9union/Ordre%20du%20Jour%2014.11%20_%20Semaine%2046.pdf[ODJ Reunion 14.11.24]
|  | https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2b12/blob/master/GPO/CR_R%C3%A9union/%20CR%20R%C3%A9union%2014.11.24%20-%20Semaine%2046.pdf[CR Reunion 14.11.24]
.1+| 47 | GPO | https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2b12/blob/master/GPO/CR_R%C3%A9union/Ordre%20du%20Jour%2022.11%20_%20Semaine%2047%20(1).pdf[ODJ Reunion 22.11.24]
.5+| 48 |GPO| https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2b12/blob/master/GPO/CR_R%C3%A9union/Ordre%20du%20Jour%2026.11%20_%20Semaine%2048.pdf[ODJ Reunion_26.11.24]
|  | https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2b12/blob/master/GPO/CR_R%C3%A9union/CR%20R%C3%A9union%2026.11%20_%20Semaine%2048.pdf[CR Reunion 26.11.24]
| PHP | SEP
|  | Charte Graphique 
|BD|https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2b12/blob/7ef83d8daef03e89bd09f7e248c551055ac69a46/solution%20web/docs/document_de_conception/SAE%20S3-03%20DevApp%20BD%20Equipe%202B12.pdf[Architecture BD : Dictionnaires Données, Diagramme de Classes, Schéma relationnel]
.4+| 49 | GPO| https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2b12/blob/master/GPO/CR_R%C3%A9union/Ordre%20du%20Jour%2004.12%20-%20Semaine%2049%20(1).pdf[ODJ Reunion 4.12.24]
|  | https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2b12/blob/master/GPO/CR_R%C3%A9union/CR%20R%C3%A9union%2004.12%20_%20Semaine%2049.pdf[CR Reunion 4.12.24]
| BD | https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2b12/blob/076a36d1b998670f0c4326e1d757a2dd9640f820/CR%20script%20SQL%20sem%2049.pdf[Script SQL]
| SYSTÈME | https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2b12/blob/076a36d1b998670f0c4326e1d757a2dd9640f820/Architecture%20Syst%C3%A8me.pdf[Architecture Système]
.4+| 50 | GPO| https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2b12/blob/380a4801f233bee4e34cb86d0253cb7ccc9d64af/GPO/CR_R%C3%A9union/Ordre%20du%20Jour%2011.12%20_Semaine%2050.pdf[ODJ Reunion 13.12.24]
|  |https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2b12/blob/828e1d70eaabfe6e7aff430ce64aaa4e62b37a2a/GPO/CR_R%C3%A9union/CR%20R%C3%A9union%2013.12%20_%20Semaine%2050.pdf[CR Reunion 13.12.24]
|SYSTÈME|https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2b12/blob/d88c4a50aaa1205e0d17c3258f764cd989741dc2/Documentation%20Partie%20Syst%C3%A8me%20V2%20-%20SAE%20S3-03%20DevApp%20Syst%C3%A8me.pdf[Documentation Système]
|iOT|https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2b12/blob/888e23322b74dafb1fa4c30da103117bf12a0803/solution%20iot/docs/doc_tech.adoc[iOT Documentation Technique]
.7+| 51 | GPO| https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2b12/blob/635602226336f2ec51c9caee5cd9242d2be626be/GPO/CR_R%C3%A9union/Ordre%20du%20Jour%2019.12%20_%20Semaine%2051.pdf[ODJ Reunion 19.12.24]
|  | https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2b12/blob/118e1295be19f20ab06fda1a9028d8b8122bf898/GPO/CR_R%C3%A9union/CR%20R%C3%A9union%2019.12%20_%20Semaine%2051.pdf[CR Reunion 19.12.24]
| | https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2b12/blob/master/GPO/CR_R%C3%A9union/Difficult%C3%A9s%20et%20r%C3%A9ussites%20-%20SYNTH%C3%88SE%20HEBDO%20ENSEIGNANT%20Semaine%2051.pdf[Analyse des difficultés et réussites Semaine 51]
| DROIT| https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2b12/blob/f6399edb212598f5924fc01d2d4b9ec4848aaa5e/Fiche%20de%20conseils%20juridiques%20et%20de%20s%C3%A9curit%C3%A9.pdf[Fiche de conseils juridiques et de sécurité]
| | https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2b12/blob/13487a84b5fe6788acb099f59f28bcbb29e5e2ff/Diagramme%20BPMN.png[Diagramme BPMN]
| BD| [Procédures stockées]
| Web|https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2b12/blob/3c3f9b7a98f4950e4d29882acecae561e5f8d0e3/solution%20web/docs/document_de_conception/Recette.adoc[Recettes]
|===

=== Documentations

Cette section regroupe les principales documentations du projet (de la conception, au développement jusqu'à l’utilisation de l’application). 

|===
|SOLUTION|DOCUMENTATION
|WEB| https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2b12/blob/master/solution%20web/docs/document_de_conception/document_conception.adoc[Document de conception]
| | https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2b12/blob/master/solution%20web/docs/document_de_conception/Documentation_utilisateur.adoc[Document Utilisateur]
| | https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2b12/blob/master/solution%20web/docs/document_de_conception/Documentation_Technique.adoc[Document Technique]
| | https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2b12/blob/3c3f9b7a98f4950e4d29882acecae561e5f8d0e3/solution%20web/docs/document_de_conception/Recette.adoc[Cahier de Recette]
|IOT|https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2b12/blob/master/solution%20iot/docs/doc_tech.adoc[iOT Documentation Technique]
|SYSTÈME|https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2b12/blob/d88c4a50aaa1205e0d17c3258f764cd989741dc2/Documentation%20Partie%20Syst%C3%A8me%20V2%20-%20SAE%20S3-03%20DevApp%20Syst%C3%A8me.pdf[Documentation Partie Système]
|===


== Communication

=== retour semaine 48

ODJ : Préciser temps de la réunion, temps consacré à chaque rubrique et qui en est responsable. CR: Manque retour reunion client et analyse : difficultés réussites du sprint. Préciser qui est responsable de la prochaine réunion.
note 1,7/3

=== retour semaine 49
ODJ : les remarques semaine 48 n'ont pas été toutes prises en compte ! CR : Très succinct !! Il manque bilan rdv client et analyse difficultés/Réussites
1,63/3

=== retour semaine 50
ODJ: manque responsable de chaque point de la réunion. CR : ok il manque l'analyse des difficultés et réussites techniques et organisationnelles
note : 2,64/3

== Gestion de projet & Qualité

Récapitulatif des informations mises à jour - Dernière MAJ : 18/12/24

✓ Version courante : https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2b12/releases[Release v0.5]

✓ Lien vers la documentation technique : https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2b12/blob/master/solution%20web/docs/document_de_conception/Documentation_Technique.adoc[Document Technique]

✓ Lien vers la documentation utilisateur : https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2b12/blob/master/solution%20web/docs/document_de_conception/Documentation_utilisateur.adoc[Document Utilisateur]

✓ Liste des (ou lien vers les) User Stories (ToDo/Ongoing/Done) et % restant : https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2b12/issues[US]

✓ Tests unitaires et plans de test : https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2b12/blob/3c3f9b7a98f4950e4d29882acecae561e5f8d0e3/solution%20web/docs/document_de_conception/Recette.adoc[Cahier de Tests]

✓ Indicateurs de qualité du code (dette technique) : 

✓ Liens vers dossier Réunions (ODJ/CR) :  https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2b12/blob/master/GPO[Dossier GPO]

=== Planning Télétravail 
Ci-dessous un récapitulatif des séances de travail effectuées en télétravail pour chaque membre de l'équipe :

|===
.2+| *MEMBRES*       4+| *SÉANCES*
                      | 29/11 (matin) | 18/12 (matin) | 19/12 (matin) | 20/12 
| Léo Guinvarc'h      | T | T | T | T
| Victor Jockin       | P | P | P | T
| Mucahit Lekesiz     | T | T | T | T
| Nolhan Biblocque    | T | P | T | T
| Mathys Laguilliez   | T | T | T | T
|===

*P :* En présentiel +
*T :* En télétravail


=== Evaluation bi-hebdomadaire

ifdef::env-github[]
image:https://docs.google.com/spreadsheets/d/e/2PACX-1vSACcYeKaH_ims3faegSLAFJ9s5_Kd9Fbyi4ODEb8BTN5OnUXWenVGhlVPo84yQDhTkTj3f9nXiluh1/pubchart?oid=935875429&amp;format=image[link=https://docs.google.com/spreadsheets/d/e/2PACX-1vSACcYeKaH_ims3faegSLAFJ9s5_Kd9Fbyi4ODEb8BTN5OnUXWenVGhlVPo84yQDhTkTj3f9nXiluh1/pubchart?oid=935875429&amp;format=image]
endif::[]

ifndef::env-github[]
++++
<iframe width="786" height="430" seamless frameborder="0" scrolling="no" src="https://docs.google.com/spreadsheets/d/e/2PACX-1vSACcYeKaH_ims3faegSLAFJ9s5_Kd9Fbyi4ODEb8BTN5OnUXWenVGhlVPo84yQDhTkTj3f9nXiluh1/pubchart?oid=935875429&amp;format=interactive"></iframe>
endif::[]

=== retour sprint 1 / Initialisation du dépôt
Enlevez les consignes du readme ! Mettre les rôles de chacun. Issues/ US :  Pensez à mettre les finalités, les critères d'acceptabilité et les tâches liées pour réaliser la US. Il faut relier votre  Backlog sprint à votre projet (créer une colonne en plus dans votre board où vous mettez les US à traiter dans le sprint). Idem il faut rattacher les tâches/issues au projet. doc: Pensez à présenter le contexte dans la doc de conception et à citer votre client. Il me manque : cahier de tests et doc utilistateur et tech à au moins initialiser à ce stade. Il me manque une release ou au moins une date de première release pour le Web.

=== Retour semaine 48

Backlog produit : il manque les finalités (afin de) dans certaines tâches et la complexité. Backlog sprint ok. Tasks : certaines en cours ne sont pas assignées. Tests : cahier à faire ! manque nom client et projet. DOCS : idem revoir infos page de garde. Avancer les doc user et tech. Conception ok manque des commentaires. release : pas de release, pas de lien vers une version courante ni de date ...
NOTE Appel Offre : 13,06/20

=== retour semaine 50
US cf retour  précédent. Je n'ai pas de backlog de sprint clair !  Le dernier date du sprint 1 !  Le cahier de recette est au point mort.  DOC user et tech à faire (pour le futur admin). Release OK.
