= Cahier De Recette - Woohp Resell
:toc:
:toc-title: Sommaire

[cols="2*"]
|===
| Projet | Développement d'un site e-commerce

| Client | Woohp Resell

| Date | Décembre 2024

|===

|===
2+^| *Equipe G2b12*
2+|
| Nom | Rôle |
https://github.com/VictorJockin[*Victor Jockin*] | *Scrum Master* |
https://github.com/34lks66[*Mucahit Lekesiz*] | *Product Owner* |
https://github.com/Hextaz[*Nolhan Biblocque*] | *Développeur* |
https://github.com/Ezeloss[*Léo Guinvarc'h*] | *Développeur* |
https://github.com/ImHereForWhat/[*Mathys Laguilliez*] | *Développeur* 
|===


== I. Introduction
=== 1. Objet :
[.text-justify]
Ce document a été produit dans le cadre d'un projet d'élaboration d'une application bancaire pour la banque DailyBank, visant à spécifier les cas de test pour assurer la qualité du site.

== II. Pre-Requis :
[.text-justify]
L'exécution des tests spécifiés au chapitre suivant requiert :

* Une base de données installée (référence document technique).
* L'environnement de test tel que spécifié dans la partie "Environnement de test" de ce document.
* Les fiches de tests. *À vérifier*


=== 1. Éléments à tester :
[.text-justify]
Les éléments testés concernent les Use-Cases spécifiés dans la *documentation technique*.


=== 2. Environnement de test :
[.text-justify]
Ordinateur sous Windows ou OS équivalent.



== III. Cas de test :
=== 1. Fonctionnalités des utilisateurs non connectés :
==== 1.1 Gestion de connexion et création de compte :

|====

>|Cas de test 4+|Test-01-01-01
>|Titre 4+|Création d'un nouveau compte
>|Objectif 4+| Vérifier qu'il est possible de créer un nouveau compte

5+|
^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_G_C.1 ^|Cliquer sur l'icône "utilisateur" dans le menu. ^|La page de connexion s'ouvre. ^| aucune ^|OK
^|All_G_C.2 ^|Cliquer sur "Créer un compte" en bas du formulaire de connexion. ^|Le formulaire de création de compte s'ouvre. ^| aucune ^|OK
^|All_G_C.3 ^|Compléter les champs spécifiés et cliquer sur le bouton "Créer". ^|Un nouveau compte client est créé et l'utilisateur est redirigé vers la page d'accueil. ^| Remplir tous les champs requis pour créer un compte ^|OK

5+|

5+|Commentaire :
Compléter et si on ne valide pas, ...
|====


|====

>|Cas de test 4+|Test-01-01-02
>|Titre 4+|Connexion à un compte 
>|Objectif 4+| Vérifier qu'il est possible de se connecter à un compte

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_G_C.3 ^|Cliquer sur l'icône "utilisateur" dans le menu. ^|La page de connexion s'ouvre. ^| aucune ^|OK
^|All_G_C.4 ^|Compléter les champs spécifiés et cliquer sur le bouton "Se connecter". ^|Connexion effectuée et l'utilisateur est redirigé vers la page d'accueil. ^|aucune ^|OK

|====


==== 1.2 Produits :


|====

>|Cas de test 4+|Test-01-02-01
>|Titre 4+|Recherche d'un produit
>|Objectif 4+| Vérifier qu'il est possible de rechercher un produit

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_G_CB.1 ^|Cliquer sur l'icône "rechercher" dans le menu. ^|La page de Recherche des produits s'ouvre. ^|Aucune ^|OK
^|All_G_CB.2 ^|Remplir la barre de recherche avec le nom du produit souhaité . ^|Les produits recherché par l'utilisateur s'affichent ^|Aucune ^|OK
...

|====

|====

>|Cas de test 4+|Test-01-02-02
>|Titre 4+|Recherche d'un produit par catégorie
>|Objectif 4+| Vérifier qu'il est possible de rechercher un produit par catégorie

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_G_CB.1 ^|Cliquer sur l'une des catégories dans le menu. Exemple: Combat, Mobilité, ... ^|La page d'affichagede tous les produits de la catégorie sélectionné s'affiche ^|Aucune ^|OK
...

|====

|====

>|Cas de test 4+|Test-01-02-03
>|Titre 4+|Consultation des détails d'un produit 
>|Objectif 4+| Vérifier qu'il est possible de consulter les détails d'un produit

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_G_CB.1 ^|Cliquer sur le produit rechercher. ^|La page permettant de consulter les détails du produit s'affiche. ^|Avoir rechercher des produits, soit par la page de recherche, soit par la page de recherche par catégorie depuis le menu. ^|OK

...

|====

|====

>|Cas de test 4+|Test-01-02-03
>|Titre 4+|Trie des produits 
>|Objectif 4+|Trier les produits par prix (Croissant ou Décroissant)

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_G_CB.1 ^|Cliquer sur le bouton "Trier par" ^|Les choix "Prix croissant" et "Prix décroissant" s'affichent ^|Aucune ^|OK
^|All_G_CB.2 ^|Sélectionner un des plusieurs trie possible et rechercher ^|Les produits recherché par l'utilisateur s'affichent par l'ordre de tri souhaité ^|Aucune ^|OK
...

|====



=== 2. Fonctionnalités des utilisateurs connectés :
[.text-justify]
Les utilisateurs connectés (client) ont accès aux mêmes fonctionnalités que les utilisateurs non connectés, ainsi que d'autres qui leur sont réservées.

==== 2.1 Gestion des comptes clients :

|====

>|Cas de test 4+|Test-02-01-01
>|Titre 4+|Consulter un compte
>|Objectif 4+| Vérifier qu'il est possible de consulter les détails d'un compte

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|C_G_C.1 ^|Cliquer sur l'icône "utilisateur" dans le menu. ^|La page visualiser_compte.php s'ouvre. ^| L'utilisateur est connecté ^|OK

5+|

5+|Commentaire : REVOIR AVEC
 *clôturés*.|

|====

|====

>|Cas de test 4+|Test-02-01-02
>|Titre 4+|Modifier un compte
>|Objectif 4+| Vérifier qu'il est possible de modifier les informations d'un compte

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|C_G_C.1    ^|Sélectionner le bouton "Inactif" et confirmer. ^|...  ^|Un client actif est sélectionné ... ^| ...

5+|

5+|Commentaire : REVOIR AVEC
 *clôturés*.|

|====

|====

>|Cas de test 4+|Test-02-01-03
>|Titre 4+|Supprimer un compte
>|Objectif 4+| Vérifier qu'il est possible de supprimer un compte

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|C_G_C.1    ^|Cliquer sur l'icône "utilisateur" dans le menu. ^|La page visualiser_compte.php s'ouvre. ^| L'utilisateur doit être connecté ^|OK
5+|

5+|Commentaire : REVOIR AVEC
 *clôturés*.|

|====

|====

>|Cas de test 4+|Test-02-01-04
>|Titre 4+|Se déconnecter d'un compte
>|Objectif 4+| Vérifier qu'il est possible de se déconnecter d'un compte

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|C_G_C.1    ^|Cliquer sur l'icône "utilisateur" dans le menu. ^|La page visualiser_compte.php s'ouvre. ^| L'utilisateur doit être connecté ^|OK
^|C_G_C.2    ^|Cliquer sur le bouton "Déconnexion". ^|L'utilisateur est redirigé vers la page d'accueil. ^| L'utilisateur doit être connecté ^|OK

5+|

5+|Commentaire : REVOIR AVEC
 *clôturés*.|

|====


==== 2.2 Gestion du panier :

|====

>|Cas de test 4+|Test-02-02-01
>|Titre 4+|Consulter le panier
>|Objectif 4+| Vérifier qu'il est possible de consulter le panier

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|C_G_C.1    ^|Cliquer sur l'icône "panier" dans le menu. ^|La page visualiser_panier.php s'ouvre. ^| L'utilisateur doit être connecté ^|OK

5+|

5+|Commentaire : REVOIR AVEC
 *clôturés*.|

|====

|====

>|Cas de test 4+|Test-02-02-02
>|Titre 4+|Ajouter un produit au panier
>|Objectif 4+| Vérifier qu'il est possible d'ajouter un produit au panier

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|C_G_C.1    ^|Sélectionner le bouton "Inactif" et confirmer. ^|...  ^|Un client actif est sélectionné ... ^| ...

5+|

5+|Commentaire : REVOIR AVEC
 *clôturés*.|

|====

==== 2.3 Gestion des commandes :

|====

>|Cas de test 4+|Test-02-03-01
>|Titre 4+|Commander un produit
>|Objectif 4+| Vérifier qu'il est possible de commander un produit
5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|C_G_C.1    ^|Cliquer sur l'icône "panier" dans le menu. ^|La page visualiser_panier.php s'ouvre. ^| L'utilisateur doit être connecté. Le panier doit comporter au moins un produit. ^|OK.
^|C_G_C.2    ^|Cliquer sur le bouton "Commander". ^|Le formulaire de commande s'ouvre. ^| Aucune ^|OK.
^|C_G_C.3    ^|Choisir le mode de livraison et le mode de paiement puis compléter les champs spécifiés et cliquer sur le bouton "Valider la commande". ^| La page confirmation_commande.php s'ouvre pour afficher un message de confirmation de commande. ^|Remplir tous les champs requis pour valider la commande. ^|OK.

5+|

5+|Commentaire : REVOIR AVEC
 *clôturés*.|

|====

==== 2.4 Gestion des avis :

|====

>|Cas de test 4+|Test-02-04-01
>|Titre 4+|Visualiser un Avis
>|Objectif 4+| Vérifier qu'il est possible de visualiser des avis

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|C_G_C.1    ^|Scroller vers le bas de la page ^|Apercevoir les avis déjà existants ^|La page de détail d'un produit doit être ouverte ^|OK

5+|

5+|Commentaire : REVOIR AVEC
 *clôturés*.|

|====

|====

>|Cas de test 4+|Test-02-04-02
>|Titre 4+|Rédiger un Avis
>|Objectif 4+| Vérifier qu'il est possible d'écrire un avis

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|C_G_C.1   ^|Scroller vers le bas de la page ^|Apercevoir le champs de rédaction d'un avis ^|La page de détail d'un produit doit être ouverte ^|OK
^|C_G_C.2    ^|Cliquer sur le champs et rédiger un avis  ^|Ajoute un avis sous le produit ^| Les notes et le champs doivent être remplis ^|OK

5+|

5+|Commentaire : REVOIR AVEC
 *clôturés*.|

|====

=== 3. Fonctionnalités des administrateurs :