= Cahier De Recette - Woohp Resell
:toc:
:toc-title: Sommaire

[cols="2*"]
|===
| Projet | Développement d'un site e-commerce

| Client | Woohp Resell

| Date | Décembre 2024

|===

|===
2+^| *Equipe G2b12*
2+|
| Nom | Rôle |
https://github.com/VictorJockin[*Victor Jockin*] | *Scrum Master* |
https://github.com/34lks66[*Mucahit Lekesiz*] | *Product Owner* |
https://github.com/Hextaz[*Nolhan Biblocque*] | *Développeur* |
https://github.com/Ezeloss[*Léo Guinvarc'h*] | *Développeur* |
https://github.com/ImHereForWhat/[*Mathys Laguilliez*] | *Développeur* 
|===


== I. Introduction
=== 1. Objet :
[.text-justify]
Ce document a été produit dans le cadre d'un projet d'élaboration d'une application bancaire pour la banque DailyBank, visant à spécifier les cas de test pour assurer la qualité du site.

== II. Pre-Requis :
[.text-justify]
L'exécution des tests spécifiés au chapitre suivant requiert :

* Une base de données installée (référence document technique).
* L'environnement de test tel que spécifié dans la partie "Environnement de test" de ce document.
* Les fiches de tests. *À vérifier*


=== 1. Éléments à tester :
[.text-justify]
Les éléments testés concernent les Use-Cases spécifiés dans la *documentation technique*.


=== 2. Environnement de test :
[.text-justify]
Ordinateur sous Windows ou OS équivalent.



== III. Cas de test :
=== 1. Fonctionnalités des utilisateurs non connectés :
==== 1.1 Gestion de connexion et création de compte :

|====

>|Cas de test 4+|Test-01-01-01
>|Titre 4+|Création d'un nouveau compte
>|Objectif 4+| Vérifier qu'il est possible de créer un nouveau compte

5+|
^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_G_C.1 ^|Cliquer sur l'icône "utilisateur" dans le menu. ^|La page de connexion s'ouvre. ^| aucune ^|OK
^|All_G_C.2 ^|Cliquer sur "Créer un compte" en bas du formulaire de connexion. ^|Le formulaire de création de compte s'ouvre. ^| aucune ^|OK
^|All_G_C.3 ^|Compléter les champs spécifiés et cliquer sur "Créer". ^|Un nouveau compte client est créé et l'utilisateur est redirigé vers la page d'accueil. ^|aucune ^|OK

5+|

5+|Commentaire :
Compléter et si on ne valide pas, ...
|====


|====

>|Cas de test 4+|Test-01-01-02
>|Titre 4+|Connexion à un compte 
>|Objectif 4+| Vérifier qu'il est possible de se connecter à un compte

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_G_C.3 ^|Cliquer sur l'icône "utilisateur" dans le menu. ^|La page de connexion s'ouvre. ^| aucune ^|OK
^|All_G_C.4 ^|Compléter les champs spécifiés et cliquer sur "Se connecter". ^|Connexion effectuée et l'utilisateur est redirigé vers la page d'accueil. ^|aucune ^|OK

|====


==== 1.2 Produits :


|====

>|Cas de test 4+|Test-01-02-01
>|Titre 4+|Recherche d'un produit
>|Objectif 4+| Vérifier qu'il est possible de rechercher un produit

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_G_CB.1 ^|Cliquer sur le bouton "Comptes client". ^|La page des comptes du client s’affiche. ^|Un client actif est sélectionné ^|OK
^|All_G_CB.2 ^|Sélectionner le bouton "Voir opérations". ^|La page des opérations du compte s’affiche. ^|Un compte actif est sélectionné ^|OK
...

|====

|====

>|Cas de test 4+|Test-01-02-02
>|Titre 4+|Recherche d'un produit par catégorie
>|Objectif 4+| Vérifier qu'il est possible de rechercher un produit par catégorie

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_G_CB.1 ^|Cliquer sur le bouton "Comptes client". ^|La page des comptes du client s’affiche. ^|Un client actif est sélectionné ^|OK
^|All_G_CB.2 ^|Sélectionner le bouton "Voir opérations". ^|La page des opérations du compte s’affiche. ^|Un compte actif est sélectionné ^|OK
...

|====

|====

>|Cas de test 4+|Test-01-02-03
>|Titre 4+|Consultation des détails d'un produit 
>|Objectif 4+| Vérifier qu'il est possible de consulter les détails d'un produit

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_G_CB.1 ^|Cliquer sur le bouton "Comptes client". ^|La page des comptes du client s’affiche. ^|Un client actif est sélectionné ^|OK
^|All_G_CB.2 ^|Sélectionner le bouton "Voir opérations". ^|La page des opérations du compte s’affiche. ^|Un compte actif est sélectionné ^|OK
...

|====



=== 2. Fonctionnalités des utilisateurs connectés :
[.text-justify]
Les utilisateurs connectés (client) ont accès aux mêmes fonctionnalités que les utilisateurs non connectés, ainsi que d'autres qui leur sont réservées.

==== 2.1 Gestion des comptes clients :

|====

>|Cas de test 4+|Test-02-01-01
>|Titre 4+|Consulter un compte
>|Objectif 4+| Vérifier qu'il est possible de consulter les détails d'un compte

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|C_G_C.1 ^|Cliquer sur l'icône "utilisateur" dans le menu. ^|La page visualiser_compte.php s'ouvre. ^| L'utilisateur est connecté ^|OK

5+|

5+|Commentaire : REVOIR AVEC
 *clôturés*.|

|====

|====

>|Cas de test 4+|Test-02-01-02
>|Titre 4+|Modifier un compte
>|Objectif 4+| Vérifier qu'il est possible de modifier les informations d'un compte

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|C_G_C.1    ^|Sélectionner le bouton "Inactif" et confirmer. ^|...  ^|Un client actif est sélectionné ... ^| ...

5+|

5+|Commentaire : REVOIR AVEC
 *clôturés*.|

|====

|====

>|Cas de test 4+|Test-02-01-03
>|Titre 4+|Supprimer un compte
>|Objectif 4+| Vérifier qu'il est possible de supprimer un compte

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|C_G_C.1    ^|Sélectionner le bouton "Inactif" et confirmer. ^|...  ^|Un client actif est sélectionné ... ^| ...

5+|

5+|Commentaire : REVOIR AVEC
 *clôturés*.|

|====

|====

>|Cas de test 4+|Test-02-01-04
>|Titre 4+|Se déconnecter d'un compte
>|Objectif 4+| Vérifier qu'il est possible de se déconnecter d'un compte

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|C_G_C.1    ^|Sélectionner le bouton "Inactif" et confirmer. ^|...  ^|Un client actif est sélectionné ... ^| ...

5+|

5+|Commentaire : REVOIR AVEC
 *clôturés*.|

|====


==== 2.2 Gestion du panier :

|====

>|Cas de test 4+|Test-02-02-01
>|Titre 4+|Consulter le panier
>|Objectif 4+| Vérifier qu'il est possible de consulter le panier

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|C_G_C.1    ^|Sélectionner le bouton "Inactif" et confirmer. ^|...  ^|Un client actif est sélectionné ... ^| ...

5+|

5+|Commentaire : REVOIR AVEC
 *clôturés*.|

|====

|====

>|Cas de test 4+|Test-02-02-02
>|Titre 4+|Ajouter un produit au panier
>|Objectif 4+| Vérifier qu'il est possible d'ajouter un produit au panier

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|C_G_C.1    ^|Sélectionner le bouton "Inactif" et confirmer. ^|...  ^|Un client actif est sélectionné ... ^| ...

5+|

5+|Commentaire : REVOIR AVEC
 *clôturés*.|

|====

==== 2.3 Gestion des commandes :

|====

>|Cas de test 4+|Test-02-03-01
>|Titre 4+|Commander un produit
>|Objectif 4+| Vérifier qu'il est possible de commander un produit
5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|C_G_C.1    ^|Sélectionner le bouton "Inactif" et confirmer. ^|...  ^|Un client actif est sélectionné ... ^| ...

5+|

5+|Commentaire : REVOIR AVEC
 *clôturés*.|

|====

==== 2.4 Gestion des avis :

=== 3. Fonctionnalités des administrateurs :