@startuml Diagramme des Cas d'Utilisation
header SAE S1.03 Conception et Développement d'Application - 2024/2025
title Diagramme des Cas d'Utilisation
/' date : 	Jeudi 7 novembre 2024	'/
/' auteur : Victor Jockin 			'/
/' équipe : 2B12					'/

/' orientation du diagramme '/
left to right direction

/' définition des acteurs '/
actor "Client non connecté"	as UtilisateurNonConnecte
actor "Client connecté"		as UtilisateurConnecte
actor Administrateur		/' administrateur du site web '/

/' construction du diagramme '/
package "Site E-Commerce" {
	package "Vitrine (Front-end)" {
		usecase (Consulter les catégories de produits) 				as UC_CCP
		usecase (Consulter la liste des produits d'une catégorie)	as UC_CLPC
		usecase (Consulter la fiche d'un produit) 					as UC_CFP
		usecase (Créer un compte)									as UC_CC
		usecase (Se connecter) 										as UC_SC
		UtilisateurNonConnecte --> UC_CCP
		UC_CCP ..> UC_CLPC
		UC_CLPC ..> UC_CFP
		UtilisateurNonConnecte --> UC_CC
		UtilisateurNonConnecte --> UC_SC
		usecase (Gérer les informations du compte)				as UC_GIC
		usecase (Visualiser l'historique des commandes passées)	as UC_VHCP
		usecase (Ajouter un avis sur un produit acheté) 		as UC_AAPA
		usecase (Gérer le panier)								as UC_GPa
		usecase (Valider une commande)							as UC_VC
		usecase (Choisir un mode de livraison)					as UC_CML
		usecase (Choisir un mode de paiement)					as UC_CMP
		UtilisateurConnecte --|> UtilisateurNonConnecte
		UC_SC --> UtilisateurConnecte
		UtilisateurConnecte --> UC_GIC
		UC_GIC ..> UC_VHCP
		UC_VHCP ..> UC_AAPA
		UtilisateurConnecte --> UC_GPa
		UC_GPa ..> UC_VC
		UC_VC ..> UC_CML : <<include>>
		UC_VC ..> UC_CMP : <<include>>
	}
	package "Espace administrateur (Back-end)" {
		usecase (Gérer les comptes utilisateurs) 	as UC_GCU
		usecase (Gérer les catégories de produits)	as UC_GCP
		usecase (Gérer les produits)				as UC_GPr
		usecase (Gérer les stocks de produits)		as UC_GSP
		usecase (Répondre aux avis clients)			as UC_RAC
		Administrateur --> UC_GCU
		Administrateur --> UC_GCP
		Administrateur --> UC_GPr
		UC_GPr ..> UC_GSP
		Administrateur --> UC_RAC
	}
}

footer BUT Informatique 2e Année, IUT de Blagnac, Université Toulouse II - Jean Jaurès (31)
@enduml