@startuml
header SAE S3.01 DevApp - 2024/2025
actor Utilisateur as u
participant "dvpvc:DataVisualisationPaneViewController" as dvpvc
participant "GraphGenerator" as gg
u -> dvpvc : displayEvolutionGraph()
dvpvc -> gg : GenerateLineChart()
dvpvc <-- gg : lineChart
u <-- dvpvc : Affichage du graphique
hide footbox
footer Victor Jockin - Équipe 2B12
@enduml