@startuml
header SAE S3.01 DevApp - 2024/2025
participant "CsvReaderTask" as csvrt
participant "dvp:DataVisualisationPane" as dvp
participant "dvpvc:DataVisualisationPaneViewController" as dvpvc
participant "UpdateDataDisplayTask" as uddt
participant "UpdateAlertDisplayTask" as uadt
participant "Thread" as thread #lightgrey
loop Exécuté périodiquement par le thread CsvReaderTask (à intervalle de temps fixe)
    csvrt -> dvp : dvp.setMap()
    dvp -> dvpvc : dvpvc.updateDataDisplay()
    dvpvc -> uddt : new UpdateDataDisplayTask(dvp, ...)
    dvpvc <-- uddt : task
    dvpvc -> thread : new Thread(task)
    dvpvc <-- thread : thread
    dvpvc -> thread : thread.start() ;
    thread -> uddt : run()
    uddt -> dvp : dvp.getDataMap()
    dvpvc <-- uddt : Mise à jour de la Table View des dernières\ndonnées reçues par capteur
    csvrt -> dvp : dvp.setAlertMap()
    dvp -> dvpvc : dvpvc.updateAlertDisplay()
    dvpvc -> uadt : new UpdateAlertDisplayTask(dvp, ...)
    dvpvc <-- uadt : task
    dvpvc -> thread : new Thread(task)
    dvpvc <-- thread : thread
    dvpvc -> thread : thread.start() ;
    thread -> uadt : run()
    uadt -> dvp : dvp.getAlertMap()
    dvpvc <-- uadt : Mise à jour du conteneur d'alertes
end
hide footbox
footer Victor Jockin - Équipe 2B12
@enduml