@startuml
header SAE S3.01 DevApp - 2024/2025
actor Utilisateur as u
participant "cffvc:ConfigurationFileFormViewController" as cffvc
participant "cff:ConfigurationFileForm" as cff
participant "config:Configuration" as config
participant "ConfigurationFileWriter" as cfw
u -> cffvc : doSave()
cff <- cffvc : enregistrerConfiguration()
cff -> config : getInstance()
cff <-- config : config
cff -> config : config.setName()
cff -> config : config.setTopicPrefix()
cff -> config : config.setSubjectList()
cff -> config : config.setDataTypeList()
cff -> config : config.setThresholdMap()
cff -> config : config.setReadingFrequency()
cff -> config : config.createFile()
config -> cfw : writeConfigurationFile(config)
cffvc -> cffvc : doClose()
u <-- cffvc : Fermeture du formulaire
hide footbox
footer Victor Jockin - Équipe 2B12
@enduml